#!/bin/bash

#branch=`git symbolic-ref HEAD`
#if [ "$branch" = "refs/heads/master" ]; then
#    echo "Direct commits to the branch master are not allowed"
#    exit 1
#fi

./node_modules/pre-commit/hook
RESULT=$?
[ $RESULT -ne 0 ] && exit 1
exit 0
