image: docker

all:
  variables:
    NVM_DIR: "/usr/local/nvm"
    NODE_VERSION: "6.9.4"
  only:
    - master
  script:
    - apt-get install -y -q --no-install-recommends \
         apt-transport-https \
         build-essential \
         ca-certificates \
         curl \
         g++ \
         gcc \
         git \
         make \
         sudo \
         wget \
         && rm -rf /var/lib/apt/lists/* \
         && apt-get -y autoclean
    - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.26.0/install.sh | bash \
          && . ./$NVM_DIR/nvm.sh \
          && nvm install $NODE_VERSION \
          && nvm alias default $NODE_VERSION \
          && nvm use default

    - npm install
    - npm test
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN -e cigit@nowhere.org registry.gitlab.com
    - docker build -t registry.gitlab.com/smart-office-iot/iot-project-server .
    - docker push registry.gitlab.com/smart-office-iot/iot-project-server