image: docker

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

build:
  stage: build
  only:
    - master
  script:
    - export IMG_VERSION=`cat package.json |grep version|cut -d ':' -f 2| sed 's/[" ,]//g'`
    - docker build --build-arg=sshKey="${SSH_PRIVATE_KEY}" --build-arg=hosts="${SSH_KNOWN_HOSTS}" -t registry.gitlab.com/smart-office-iot/iot-project-server:${IMG_VERSION} .
    - docker build --build-arg=sshKey="${SSH_PRIVATE_KEY}" --build-arg=hosts="${SSH_KNOWN_HOSTS}" -t registry.gitlab.com/smart-office-iot/iot-project-server:latest .

    - docker push registry.gitlab.com/smart-office-iot/iot-project-server:${IMG_VERSION}
    - docker push registry.gitlab.com/smart-office-iot/iot-project-server:latest
