image: docker

services:
  - docker:dind

build:
  stage: build
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/smart-office-iot/iot-project-server .
    - docker push registry.gitlab.com/smart-office-iot/iot-project-server