image: docker

all:
  variables:
    NVM_DIR: "/usr/local/nvm"
    NODE_VERSION: "6.9.4"
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN -e cigit@nowhere.org registry.gitlab.com
    - docker build -t registry.gitlab.com/smart-office-iot/iot-project-server .
    - docker push registry.gitlab.com/smart-office-iot/iot-project-server