image: docker

all:
  only:
    - master
  script:
    - npm install
    - npm test
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN -e cigit@nowhere.org registry.gitlab.com
    - docker build -t registry.gitlab.com/smart-office-iot/iot-project-server .
    - docker push registry.gitlab.com/smart-office-iot/iot-project-server

